In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\padma\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\padma\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\padma\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\padma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\padma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\padma\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
s1=pd.Series([1,2,3,4,5,6])

In [4]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
type(s1)

pandas.core.series.Series

In [6]:
s1=pd.Series([1,2,3,4],index=["a","b","c","d"])

In [7]:
s1

a    1
b    2
c    3
d    4
dtype: int64

# dataframe 2d array

In [8]:
data={"name":["alice","bob","charlie"],"age":[20,23,24],"city":["mumbai","delhi","banglr"]}

In [9]:
data

{'name': ['alice', 'bob', 'charlie'],
 'age': [20, 23, 24],
 'city': ['mumbai', 'delhi', 'banglr']}

In [10]:
type(data)

dict

In [11]:
df=pd.DataFrame(data)

In [12]:
df

      name  age    city
0    alice   20  mumbai
1      bob   23   delhi
2  charlie   24  banglr

In [13]:
df=pd.DataFrame(data,index=["person1","person2","person3"])

In [14]:
df

            name  age    city
person1    alice   20  mumbai
person2      bob   23   delhi
person3  charlie   24  banglr

In [15]:
df.index

Index(['person1', 'person2', 'person3'], dtype='object')

In [16]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

# creating dataframe from list

In [17]:
data=([1,2,3],[4,5,6])

In [18]:
data

([1, 2, 3], [4, 5, 6])

In [19]:
df=pd.DataFrame(data,columns=["A","B","C"],index=["D","E"])

In [20]:
df

   A  B  C
D  1  2  3
E  4  5  6

In [21]:
df=pd.read_excel(r"C:\Users\padma\Documents\Book1.xlsx")

In [22]:
df

      name  school  marks
0  shubham   dsjds     67
1      dia  dvfvfb     45
2      ria     sag     98
3      sam     hnf      5
4      ram    dass     67

In [23]:
df=pd.read_json(r"C:\Users\padma\Downloads\book2.json")

In [24]:
df

    name    lang
0  alice  python
1    bob    html

In [25]:
import pandas as pd
df=pd.read_csv("Book1.csv")
df.head()

      name  school  marks
0  shubham   dsjds     67
1      dia  dvfvfb     45
2      ria     sag     98
3      sam     hnf      5
4      ram    dass     67

In [26]:
iris='http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df=pd.read_csv(iris)

In [27]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [28]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [29]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [30]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [31]:
df.shape

(149, 5)

In [32]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

# Data Selection

In [34]:
import pandas as pd

In [35]:
df=pd.read_csv("data2.csv")

In [36]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [37]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [38]:
type(df["Actor"])

pandas.core.series.Series

In [39]:
df[["Actor","IMDb"]]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [40]:
type(df[["Actor","IMDb"]])

pandas.core.frame.DataFrame

In [41]:
df.loc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [42]:
df.iloc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [43]:
df1=pd.DataFrame([[1,2,3],[4,5,6]],columns=["A","B","C"],index=["D","E"])

In [44]:
df1

   A  B  C
D  1  2  3
E  4  5  6

In [45]:
df1.iloc[0]

A    1
B    2
C    3
Name: D, dtype: int64

In [46]:
df1.loc["D"]

A    1
B    2
C    3
Name: D, dtype: int64

In [47]:
df.loc[0,"Actor"]

'Shah Rukh Khan'

In [48]:
df.iloc[0,0]

'Shah Rukh Khan'

In [49]:
df.loc[0:2,["Actor","IMDb"]]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [50]:
df.iloc[0:2,[0,5]]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0

In [51]:
df.loc[0:2,"Actor":"Genre"]

            Actor             Film  Year      Genre
0  Shah Rukh Khan          Pathaan  2023     Action
1     Salman Khan  Tiger Zinda Hai  2017     Action
2      Aamir Khan           Dangal  2016  Biography

In [52]:
df.iloc[0:3,0:4]

            Actor             Film  Year      Genre
0  Shah Rukh Khan          Pathaan  2023     Action
1     Salman Khan  Tiger Zinda Hai  2017     Action
2      Aamir Khan           Dangal  2016  Biography

# fast access at and iat

In [53]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [54]:
df.iat[0,0]

'Shah Rukh Khan'

# data filtering

In [55]:
df["IMDb"]>6

0      True
1     False
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
Name: IMDb, dtype: bool

In [56]:
df["IMDb"]<6

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
Name: IMDb, dtype: bool

In [57]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [58]:
df[(df["Year"]>2017)&(df["IMDb"]>6)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [59]:
df[(df["Year"]>2019)&(df["IMDb"]>6)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [60]:
df.query("Year>2017 & IMDb>6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [61]:
df.query("Year>2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [62]:
df.query('Actor=="Hrithik Roshan"')

            Actor Film  Year   Genre  BoxOffice(INR Crore)  IMDb
7  Hrithik Roshan  War  2019  Action                   475   6.5

In [63]:
df1=pd.DataFrame([[1,2,3],[4,5,6]],columns=["A B","C","D"])

In [64]:
df1

   A B  C  D
0    1  2  3
1    4  5  6

In [65]:
df1.query("`A B`==1")

   A B  C  D
0    1  2  3

In [66]:
year=2017
df.query("Year > @year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [67]:
df.query("2017 < Year < 2022")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# data cleaning and preprocessing

In [68]:
import pandas as pd

In [69]:
df=pd.read_csv("data_cleaning_sample.csv")

In [70]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

# handling missing data

In [71]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [72]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

# drop missing data

In [73]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [74]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [75]:
df.drop([0,3])               # remove particular rows

      Name   Age         City Gender              Email   Join Date
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [76]:
df.drop(columns=["Age","Name","City"])

  Gender              Email   Join Date
0      F  alice@example.com    1/5/2021
1      M    charlie@example  20-07-2021
2      M    bob@example.com  15-06-2020
3      M    charlie@example  20-07-2021
4      M  david@example.com  12/11/2019
5      F     eve@domain.com         NaN
6      F  alice@example.com    1/5/2021
7      F  alice@example.com    1/5/2021
8      M    charlie@example  20-07-2021

# filling missing values

In [77]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [78]:
df["Age"].fillna(df["Age"].mean().astype(int))

0    25.0
1    25.0
2    30.0
3    25.0
4    22.0
5    28.0
6    25.0
7    25.0
8    25.0
Name: Age, dtype: float64

In [79]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    David  28.0        Delhi      F     eve@domain.com  12/11/2019
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [80]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    Alice  28.0        Delhi      F     eve@domain.com    1/5/2021
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

# detecting and removing duplicates

In [81]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [82]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [83]:
df.drop_duplicates(subset="Name")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

# string operators with str

In [84]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [85]:
df["City"].str.contains("dehli",case=True)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: City, dtype: bool

In [86]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

# applying function

In [87]:
df1=df.drop_duplicates()

In [88]:
import warnings
warnings.filterwarnings("ignore")

In [89]:
df1["Age Group"]=df1["Age"].apply(lambda x : "Adult" if x>=25 else "Minor")

In [90]:
df1

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai      M  david@example.com  12/11/2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult

In [91]:
df1["Gender"] = df1["Gender"].map({"M": "Male", "F": "Female"})

In [92]:
df1

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com    1/5/2021     Adult
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai    Male  david@example.com  12/11/2019     Minor
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult

In [93]:
df["City"]=df["City"].replace({"New York":"US","Mumbai":"Dehli"})

In [94]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0           US      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0        Dehli      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0           US      F  alice@example.com    1/5/2021
7    Alice  25.0           US      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021